travis:
  secure:
    BINSTAR_TOKEN: wphlOgYOsqP9AEJlW1q2xDnKRtzsOB5aR632QtbMdLoXM0jQm7Z3jg8g802sqa/Q71ZKMrB7i+e2dRtVF2H3g06qxlyrTpN8Mc48aattErMTT3C7hAPq2+YKZ+euzua3kF3W5HbWTgx9UpOf+gigjRjznj5pelk+0tq6LmUMW0QtVuQ13xoPqjXJRph6WQDZjVrlz5WOncbG29cj9MZYtn9GagWGyAlfM8yX55w3SMl9YEzz6L/h107xynKniOmfwZzGaz8CKiCsUSNJ8uF/7Shnw6NTYph5AA6qSPw8qknTmHdp/kDMG8cEKx/sid/gXbaw5kubYVq6W3hTNKf0LD4LbOlDNdFdSts+cQwxwUQxzFCtE7RRzJycCnCD7BH47xzTt5vre4yp7/I+RL9S3ShhQAUpxRSMwIvNZ/JHQLvq1DSf3pXa0plBZrmEEGFgHJMSqSGCtb2mdZdUUD1fMqn0SRgKWFjOC5SIqL6Qscp6ikuZgjRQdxLt3N8DQvNzGqhj3qb+iocOYTXzxjteGs6q9W1BLgERZpFqXbukFmve8Om4u/zQfFuDqIPf1iza55bjRo4DJVILuK7JQ+UU47opJUJEZHFB6li+MasHA8pspaU8mMCC4l0p6p0x3CPlPLzwuOmQUhegvwkFXtf0pptWHsLYnbFKX2fBbwdW7pA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
